### ISSUE TITLE
Namespace errors

### ISSUE THREAD

**Issue by SDenman** [danaki/doctrine-enum-type-bundle#1]
Hi there,
Sorry in advance if this is a dumb question

I was giving this a try as a potentially cleaner way to get  [myclabs/php-enum](https://github.com/myclabs/php-enum) and [acelaya/doctrine-enum-type](https://github.com/acelaya/doctrine-enum-type) up and running with a Symfony 4 project I'm working on, but couldn't get it to load properly.
I've tried cloning the bundle under vendors and adding the following reference under config/bundles.php:
Danaki\DoctrineEnumTypeBundle\DanakiDoctrineEnumTypeBundle::class => ['all' => true]

But it still throws an error:
--------------------
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DanakiDoctrineEnumTypeBundle" from namespace "Danaki\DoctrineEnumTypeBundle".
Did you forget a "use" statement for another namespace? in /srv/api/src/Kernel.php:33
Stack trace:
#0 /srv/api/vendor/symfony/http-kernel/Kernel.php(405): App\Kernel->registerBundles()
#1 /srv/api/vendor/symfony/http-kernel/Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /srv/api/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /srv/api/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /srv/api/bin/console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /srv/api/src/Kernel.php on line 33
---------------

I'm wondering if it's related to the fact that DanakiDoctrineEnumTypeBundle.php has a reference to the container that doesn't seem to have been injected.

Any ideas? Or did you find another way to work with enums in Symfony 4?

**Comment by danaki** [comment]
Try composer.json approach given in Installation section of README. Cloning the bundle under vendor definitely won't work.

**Comment by SDenman** [comment]
OK, so sorry to bother you, don't know what I did wrong the first time, but when I tried that again, it worked perfectly :)

**Comment by danaki** [comment]
https://packagist.org/packages/danaki/doctrine-enum-type-bundle if you're still interested
