### ISSUE TITLE
Please release on Packagist

### ISSUE THREAD

**Issue by gronostajo** [danaki/doctrine-enum-type-bundle#2]
The package seems to work for me. I'd love to have it available on Packagist and properly tagged so that I don't have `dev-master` in my composer.json. Please release it!

**Comment by danaki** [comment]
The whole package is about 10 lines of code :) Ok, how do I start with Packagist?

**Comment by gronostajo** [comment]
Packagist has a pretty good guide on [their homepage](https://packagist.org/). Nothing too complicated. You already have `composer.json` in the project, so I guess you just have to tag the release on GitHub and submit it to Packagist. Don't quote me on this though, I've only did it once and it was a while ago :)

**Comment by danaki** [comment]
Here, https://packagist.org/packages/danaki/doctrine-enum-type-bundle does it work for you?

**Comment by gronostajo** [comment]
Yup, it installs and seems to work. Thanks!

You could update the README, now just `composer require danaki/doctrine-enum-type-bundle` will be sufficient without editing `composer.json` manually.

**Comment by danaki** [comment]
Right, thanks, almost forgot about that
